//
// Generated by afu_json_mgr from ../../bdx-rtl.json
//

#ifndef __AFU_JSON_INFO__
#define __AFU_JSON_INFO__

#define AFU_ACCEL_NAME "bdx-rtl"
#define AFU_ACCEL_UUID 128'h23f23a41_42b4_4acc_84cb_817bb75b35b1
#define AFU_IMAGE_POWER 0
#define AFU_TOP_IFC "ofs_plat_afu"

#endif // __AFU_JSON_INFO__
